import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import AnimateContainer from "@/components/AnimateContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				{/* <AnimateContainer> */}
				<Navbar />
				{children}
				<Footer />
				{/* </AnimateContainer> */}
			</body>
		</html>
	);
}
